spring.application.name=rate-provider
spring.main.banner-mode=off
server.port=${PROVIDER_PORT:8081}
discovery.enabled=true
discovery.address=${ZOOKEEPER_ADDRESS:localhost:22181}
discovery.path=/services/currency-http
discovery.advertised-host=${PROVIDER_HOST:localhost}
logging.level.org.apache.zookeeper=WARN
logging.level.org.apache.curator=WARN
logging.level.root=INFO

management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
metrics.clients=${METRICS_CLIENTS:rate-printer,manual}
