global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: spring
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['service1:8080']
        labels: {service: service1}
      - targets: ['service2:8080']
        labels: {service: service2}
      - targets: ['client:8080']
        labels: {service: client}
  - job_name: zookeeper
    static_configs:
      - targets: ['zookeeper:7070']
        labels: {service: zookeeper}
