spring.application.name=rate-printer
spring.main.banner-mode=off
spring.main.web-application-type=none
discovery.address=${ZOOKEEPER_ADDRESS:localhost:22181}
discovery.path=/services/currency-http
logging.level.org.apache.zookeeper=WARN
logging.level.org.apache.curator=WARN
logging.level.root=INFO
